# Generated by Django 2.1.7 on 2019-03-16 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_id', models.CharField(max_length=200)),
                ('turn_id', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('intent', models.CharField(max_length=100)),
                ('ner', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
